# Default values for afraid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: curlimages/curl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

cronjob:
  schedule: "*/5 * * * *"
  annotations: {}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  restartPolicy: OnFailure

afraid:
  token: "QmVTMzZWVmdnbmlCdG1WbHQzbGM6MTk5NDU0NTU"
