apiVersion: v1
kind: Secret
metadata:
  name: {{ include "afraid.fullname" . }}
  labels:
    {{- include "afraid.labels" . | nindent 4 }}
type: Opaque
data:
  afraid-token: {{ .Values.afraid.token | b64enc | quote }}
